name: cellbender_merge
description: Module to use CellBender to remove ambient RNA from single-cell RNA-seq data
keywords:
  - single-cell
  - scRNA-seq
  - ambient RNA removal
tools:
  - cellbender:
      description: CellBender is a software package for eliminating technical artifacts from high-throughput single-cell RNA sequencing (scRNA-seq) data.
      documentation: https://cellbender.readthedocs.io/en/latest/
      tool_dev_url: https://github.com/broadinstitute/CellBender
      licence:
        - "BSD-3-Clause"
      identifier: biotools:CellBender
input:
  - - meta:
        type: map
        description: Groovy Map containing sample information, e.g. [ id:'test' ]
    - filtered:
        type: file
        description: AnnData file containing filtered data (without empty droplets)
        pattern: "*.h5ad"
        ontologies: []
    - unfiltered:
        type: file
        description: AnnData file containing unfiltered data (with empty droplets)
        pattern: "*.h5ad"
        ontologies: []
    - cellbender_h5:
        type: file
        description: CellBender h5 file containing ambient RNA estimates
        pattern: "*.h5"
        ontologies: []
  - output_layer_name:
      type: string
      description: The name of the layer to store counts
output:
  h5ad:
    - - meta:
          type: map
          description: Groovy Map containing sample information
      - ${prefix}.h5ad:
          type: file
          description: AnnData file containing decontaminated counts as `adata.X`
          pattern: "*.h5ad"
          ontologies: []
  versions_cellbender:
    - versions.yml:
        type: file
        description: File containing software version
        pattern: "versions.yml"
        ontologies:
          - edam: http://edamontology.org/format_3750
topics:
  versions:
    - versions.yml:
        type: file
        description: File containing software version
        pattern: "versions.yml"
        ontologies:
          - edam: http://edamontology.org/format_3750
authors:
  - "@nictru"
maintainers:
  - "@nictru"
  - "@jaredfischbach"
containers:
  docker:
    linux/arm64:
      name: community.wave.seqera.io/library/cellbender_python_webcolors:388f6c567173b773
      build_id: bd-388f6c567173b773_1
      scan_id: sc-ae64248a6fe95bb0_1
    linux/amd64:
      name: community.wave.seqera.io/library/cellbender_python_webcolors:a114221c4c31ab91
      build_id: bd-a114221c4c31ab91_1
      scan_id: sc-6496743368797852_1
  singularity:
    linux/arm64:
      name: oras://community.wave.seqera.io/library/cellbender_python_webcolors:ac806304d9d36151
      build_id: bd-ac806304d9d36151_1
      https: https://community-cr-prod.seqera.io/docker/registry/v2/blobs/sha256/90/90832edebede0b11e89fe536ee93b466345bc819a19e09306999ea089da76f12/data
    linux/amd64:
      name: oras://community.wave.seqera.io/library/cellbender_python_webcolors:66fc70090a0259d9
      build_id: bd-66fc70090a0259d9_1
      https: https://community-cr-prod.seqera.io/docker/registry/v2/blobs/sha256/b0/b01fb7d6f34ec2485438a09ad1494aa2c897a9b793069f9caef677bcd8d6784d/data
  conda:
    linux/amd64:
      lock_file: modules/nf-core/cellbender/merge/.conda-lock/linux_amd64-bd-a114221c4c31ab91_1.txt
    linux/arm64:
      lock_file: modules/nf-core/cellbender/merge/.conda-lock/linux_arm64-bd-388f6c567173b773_1.txt
